//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2022. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

using System.Configuration;
using System.Drawing;
using System.Linq;

namespace System.Windows.Forms
{
    public partial class AddNewItemDialog : ApplicationForm
    {
        public AddNewItemDialog()
        {
            InitializeComponent();

            ShowFooter = true;
            ShowHeader = true;

            MaximizeBox = false;
            MinimizeBox = false;

            Size = new Size(610, 480);
            MinimumSize = new Size(610, 480);
            MaximumSize = ApplicationAppereance.Sizes.DialogMaximumSize;

            SplitEdit.Padding = new Padding(6);
            SplitEdit.Panel1.Width = 230;
            SplitEdit.Panel1.MinWidth = 200;
            SplitEdit.Panel1.MaxWidth = (int)(Width * 0.6);

            ListEdit.DoubleClick += OnProviderDoubleClick;
            ListEdit.View.SelectedIndexChanged += OnSelectedItemChanged;
        }

        [ConfigurationValue]
        public int LeftPanelWidth
        {
            get { return SplitEdit.Panel1.Width; }
            set { SplitEdit.Panel1.Width = value; }
        }

        public ListViewEdit List
        {
            get { return ListEdit; }
        }

        public Control PropertiesControl
        {
            get { return SplitEdit.Panel2.Controls.Cast<Control>().FirstOrDefault(); }
            set
            {
                if (PropertiesControl.HasValue())
                {
                    using (PropertiesControl)
                    {
                        SplitEdit.Panel2.Controls.Clear();
                    }
                }

                if (value.HasValue())
                {
                    SplitEdit.Panel2.Controls.Add(value);
                }
            }
        }

        private SplitEdit SplitEdit;
        private ListViewEdit ListEdit;

        protected virtual void OnSelectedItemChanged(object sender, EventArgs e)
        {
            ValidateForm();
        }

        protected virtual void OnProviderDoubleClick(object sender, EventArgs e)
        {
            Footer.Buttons["OK"].PerformClick();
        }

        protected virtual void ValidateForm()
        {
        }

        protected override void OnVisibleChanged(EventArgs e)
        {
            if (ListEdit.View.SelectedRow < 0)
            {
                ListEdit.View.SelectedRow = 0;
            }

            base.OnVisibleChanged(e);
        }

        void InitializeComponent()
        {
            this.SplitEdit = new System.Windows.Forms.SplitEdit();
            this.ListEdit = new System.Windows.Forms.ListViewEdit();
            this.SplitEdit.Panel1.SuspendLayout();
            this.SplitEdit.SuspendLayout();
            this.SuspendLayout();
            // 
            // SplitEdit
            // 
            this.SplitEdit.Dock = System.Windows.Forms.DockStyle.Fill;
            this.SplitEdit.Location = new System.Drawing.Point(2, 152);
            this.SplitEdit.Name = "SplitEdit";
            // 
            // SplitEdit.Panel1
            // 
            this.SplitEdit.Panel1.Controls.Add(this.ListEdit);
            this.SplitEdit.Panel1.Name = "Panel1";
            // 
            // SplitEdit.Panel2
            // 
            this.SplitEdit.Panel2.Name = "Panel2";
            this.SplitEdit.Size = new System.Drawing.Size(496, 246);
            this.SplitEdit.TabIndex = 3;
            this.SplitEdit.TabStop = false;
            this.SplitEdit.Text = "splitEdit1";
            // 
            // ListEdit
            // 
            this.ListEdit.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ListEdit.Location = new System.Drawing.Point(0, 0);
            this.ListEdit.Name = "ListEdit";
            this.ListEdit.Padding = new System.Windows.Forms.Padding(1);
            this.ListEdit.Size = new System.Drawing.Size(120, 246);
            this.ListEdit.TabIndex = 0;
            this.ListEdit.TabStop = false;
            this.ListEdit.Text = "listViewEdit1";
            // 
            // AddNewItemDialog
            // 
            this.ClientSize = new System.Drawing.Size(500, 400);
            this.Body.Controls.Add(this.SplitEdit);
            this.Name = "AddNewItemDialog";
            this.SplitEdit.Panel1.ResumeLayout(false);
            this.SplitEdit.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
