//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2022. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

using System.Configuration;
using System.Resources;
using System.Runtime.InteropServices;

namespace System.Windows.Forms
{
    [Guid("B3DCDFEB-D862-4C62-A396-5072580EF5C9")]
    internal class ApplicationSubscriptionDialog : ApplicationForm
    {
        private LabelEdit LabelUser;
        private LabelEdit LabelPassword;
        private TextEdit Password;
        private ImageEdit LogonImage;
        private TextEdit UserName;
        private LanguageButtonEdit LanguageButton;

        public ApplicationSubscriptionDialog()
        {
            InitializeComponent();

            ShowIcon = true;
            ShowInTaskbar = true;
            Footer.Buttons["OK"].Enabled = false;
            LogonImage.Image = Images048.CheckedUser;
            StartPosition = FormStartPosition.CenterScreen;

            UserName.TextChanged += OnUserTextChanged;
            Password.TextChanged += OnUserTextChanged;

            Localization.Register(this, (e) => LabelUser.Text = e("UserName"));
            Localization.Register(this, (e) => LabelPassword.Text = e("Password"));

            Localization.Register(this, (e) => HeaderCaption = e("ApplicationSubscription.Caption"));
            Localization.Register(this, (e) => HeaderTitle = e("ApplicationSubscription.Title"));
        }

        protected void OnUserTextChanged(object sender, EventArgs e)
        {
            Footer.Buttons["OK"].Enabled = UserName.Text.Length >= 6 && Password.Text.Length >= 6;
        }

        protected override string ProductLicense
        {
            get { return string.Empty; }
        }

        [ConfigurationValue]
        public string User
        {
            get { return UserName.EditValue as string; }
            set
            {
                UserName.EditValue = value;

                if (!string.IsNullOrEmpty(value))
                {
                    Password.Select();
                }
            }
        }

        void InitializeComponent()
        {
            this.UserName = new System.Windows.Forms.TextEdit();
            this.LabelUser = new System.Windows.Forms.LabelEdit();
            this.Password = new System.Windows.Forms.TextEdit();
            this.LabelPassword = new System.Windows.Forms.LabelEdit();
            this.LogonImage = new System.Windows.Forms.ImageEdit();
            this.LanguageButton = new System.Windows.Forms.LanguageButtonEdit();
            this.BodyControl.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.LogonImage)).BeginInit();
            this.SuspendLayout();
            // 
            // BodyControl
            // 
            this.BodyControl.Controls.Add(this.LanguageButton);
            this.BodyControl.Controls.Add(this.LogonImage);
            this.BodyControl.Controls.Add(this.LabelPassword);
            this.BodyControl.Controls.Add(this.LabelUser);
            this.BodyControl.Controls.Add(this.Password);
            this.BodyControl.Controls.Add(this.UserName);
            this.BodyControl.Padding = new System.Windows.Forms.Padding(6);
            // 
            // UserName
            // 
            this.UserName.Location = new System.Drawing.Point(221, 44);
            this.UserName.MaxLength = 32767;
            this.UserName.MinimumSize = new System.Drawing.Size(16, 22);
            this.UserName.Name = "UserName";
            this.UserName.Padding = new System.Windows.Forms.Padding(3);
            this.UserName.Size = new System.Drawing.Size(186, 22);
            this.UserName.TabIndex = 0;
            this.UserName.Text = "";
            // 
            // LabelUser
            // 
            this.LabelUser.Location = new System.Drawing.Point(126, 46);
            this.LabelUser.Name = "LabelUser";
            this.LabelUser.Padding = new System.Windows.Forms.Padding(3);
            this.LabelUser.Size = new System.Drawing.Size(72, 17);
            this.LabelUser.TabIndex = 1;
            this.LabelUser.TabStop = false;
            this.LabelUser.Text = "Kullanıcı Adı";
            this.LabelUser.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // Password
            // 
            this.Password.IsPassword = true;
            this.Password.Location = new System.Drawing.Point(221, 72);
            this.Password.MaxLength = 32767;
            this.Password.MinimumSize = new System.Drawing.Size(16, 22);
            this.Password.Name = "Password";
            this.Password.Padding = new System.Windows.Forms.Padding(3);
            this.Password.Size = new System.Drawing.Size(186, 22);
            this.Password.TabIndex = 2;
            this.Password.Text = "";
            // 
            // LabelPassword
            // 
            this.LabelPassword.Location = new System.Drawing.Point(126, 74);
            this.LabelPassword.Name = "LabelPassword";
            this.LabelPassword.Padding = new System.Windows.Forms.Padding(3);
            this.LabelPassword.Size = new System.Drawing.Size(39, 17);
            this.LabelPassword.TabIndex = 3;
            this.LabelPassword.TabStop = false;
            this.LabelPassword.Text = "Şifre";
            this.LabelPassword.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // LogonImage
            // 
            this.LogonImage.Location = new System.Drawing.Point(50, 44);
            this.LogonImage.Name = "LogonImage";
            this.LogonImage.Size = new System.Drawing.Size(52, 52);
            this.LogonImage.TabIndex = 4;
            this.LogonImage.TabStop = false;
            // 
            // LanguageButton
            // 
            this.LanguageButton.Location = new System.Drawing.Point(440, 123);
            this.LanguageButton.Name = "LanguageButton";
            this.LanguageButton.Size = new System.Drawing.Size(30, 24);
            this.LanguageButton.TabIndex = 5;
            this.LanguageButton.TabStop = false;
            // 
            // ApplicationSubscriptionDialog
            // 
            this.ClientSize = new System.Drawing.Size(485, 300);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.HeaderCaption = "GISExpress Aktivasyon";
            this.HeaderTitle = "GISExpress ürün kopyanızı etkinleştirmek için aşağıdaki bilgileri giriniz";
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.MinimumSize = new System.Drawing.Size(485, 300);
            this.Name = "ApplicationSubscriptionDialog";
            this.Padding = new System.Windows.Forms.Padding(6);
            this.ShowFooter = true;
            this.ShowHeader = true;
            this.ShowIcon = false;
            this.ShowInTaskbar = true;
            this.Controls.SetChildIndex(this.CaptionControl, 0);
            this.Controls.SetChildIndex(this.BodyControl, 0);
            this.BodyControl.ResumeLayout(false);
            this.BodyControl.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.LogonImage)).EndInit();
            this.ResumeLayout(false);

        }
    }
}
