//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2022. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

using System.Configuration;

namespace System.Windows.Forms
{
    public class LicenseAgreementDialog : ApplicationForm
    {
        static LicenseAgreementDialog()
        {
            Default = new LicenseAgreementDialog();
        }

        public LicenseAgreementDialog()
        {
            InitializeComponent();

            FormBorderStyle = FormBorderStyle.FixedSingle;
            StartPosition = FormStartPosition.CenterScreen;

            RadioYes.CheckedChanged += OnCheckedChanged;
            RadioNo.CheckedChanged += OnCheckedChanged;
            ButtonLang.Click += OnLanguageClick;

            OnLanguageClick(this, EventArgs.Empty);

            Localization.Register(this, e => Header.Caption = e("LicenseAgreement"));
            Localization.Register(this, e => Header.Title = e("LicenseAgreement.Title"));

            Localization.Register(this, e => RadioYes.Text = e("LicenseAgreement.Yes"));
            Localization.Register(this, e => RadioNo.Text = e("LicenseAgreement.No"));

            if (ApplicationConfiguration.Current.Security.Agreed)
            {
                RadioYes.Checked = true;
            }
            else
            {
                Footer.Buttons["OK"].Enabled = false;
            }

            Agreement.BringToFront();
            RadioPanel.SendToBack();
        }

        public static readonly LicenseAgreementDialog Default;

        protected RichTextEdit Agreement;
        protected CheckEdit RadioYes;
        protected CheckEdit RadioNo;
        protected LanguageButtonEdit ButtonLang;
        protected TablePanelEdit RadioPanel;

        public static void Register()
        {
            // This method exists to call static constructor
        }

        protected override void OnShown(EventArgs e)
        {
            Activate();
            base.OnShown(e);
        }

        protected void OnLanguageClick(object sender, EventArgs e)
        {
            Agreement.Text = ApplicationEnvironment.GetType("System.Security.Eula, System.Security").GetPropertyValue<string>("Agreement");
        }

        protected void OnCheckedChanged(object sender, EventArgs e)
        {
            var edit = sender as CheckEdit;

            if (edit.HasValue())
            {
                Footer.Buttons["OK"].Enabled = ApplicationConfiguration.Current.Security.Agreed || (edit.Name.Equals("RadioYes") && edit.Checked);
            }
        }

        public static bool IsAccepted(IWin32Window owner)
        {
            if (Default.ShowDialog(owner) == DialogResult.OK)
            {
                ApplicationConfiguration.Current.Security.Agreed = Default.RadioYes.Checked;
                ApplicationConfiguration.Current.Save();
            }

            return ApplicationConfiguration.Current.Security.Agreed;
        }

        void InitializeComponent()
        {
            this.RadioPanel = new System.Windows.Forms.TablePanelEdit();
            this.RadioYes = new System.Windows.Forms.CheckEdit();
            this.ButtonLang = new System.Windows.Forms.LanguageButtonEdit();
            this.RadioNo = new System.Windows.Forms.CheckEdit();
            this.Agreement = new System.Windows.Forms.RichTextEdit();
            this.BodyControl.SuspendLayout();
            this.RadioPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // BodyControl
            // 
            this.BodyControl.Controls.Add(this.RadioPanel);
            this.BodyControl.Controls.Add(this.Agreement);
            this.BodyControl.Padding = new System.Windows.Forms.Padding(3);
            // 
            // RadioPanel
            // 
            this.RadioPanel.AutoSize = true;
            this.RadioPanel.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.RadioPanel.ColumnCount = 3;
            this.RadioPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.RadioPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.RadioPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 48F));
            this.RadioPanel.Controls.Add(this.RadioYes, 0, 0);
            this.RadioPanel.Controls.Add(this.ButtonLang, 2, 0);
            this.RadioPanel.Controls.Add(this.RadioNo, 1, 0);
            this.RadioPanel.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.RadioPanel.Location = new System.Drawing.Point(3, 357);
            this.RadioPanel.Name = "RadioPanel";
            this.RadioPanel.RowCount = 1;
            this.RadioPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 36F));
            this.RadioPanel.Size = new System.Drawing.Size(588, 36);
            this.RadioPanel.TabIndex = 0;
            // 
            // RadioYes
            // 
            this.RadioYes.Checked = false;
            this.RadioYes.Dock = System.Windows.Forms.DockStyle.Fill;
            this.RadioYes.IsRadio = true;
            this.RadioYes.Location = new System.Drawing.Point(3, 3);
            this.RadioYes.Name = "RadioYes";
            this.RadioYes.RadioGroupIndex = 1;
            this.RadioYes.Size = new System.Drawing.Size(264, 30);
            this.RadioYes.TabIndex = 0;
            this.RadioYes.Text = "";
            this.RadioYes.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // ButtonLang
            // 
            this.ButtonLang.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.ButtonLang.Location = new System.Drawing.Point(543, 6);
            this.ButtonLang.Name = "ButtonLang";
            this.ButtonLang.Size = new System.Drawing.Size(42, 23);
            this.ButtonLang.TabIndex = 2;
            // 
            // RadioNo
            // 
            this.RadioNo.Checked = false;
            this.RadioNo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.RadioNo.IsRadio = true;
            this.RadioNo.Location = new System.Drawing.Point(273, 3);
            this.RadioNo.Name = "RadioNo";
            this.RadioNo.RadioGroupIndex = 1;
            this.RadioNo.Size = new System.Drawing.Size(264, 30);
            this.RadioNo.TabIndex = 1;
            this.RadioNo.Text = "";
            this.RadioNo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // Agreement
            // 
            this.Agreement.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Agreement.FontSize = 10.25F;
            this.Agreement.Location = new System.Drawing.Point(3, 3);
            this.Agreement.Name = "Agreement";
            this.Agreement.Padding = new System.Windows.Forms.Padding(6, 6, 1, 6);
            this.Agreement.Size = new System.Drawing.Size(588, 390);
            this.Agreement.TabIndex = 1;
            this.Agreement.TabStop = false;
            // 
            // LicenseAgreementDialog
            // 
            this.ClientSize = new System.Drawing.Size(600, 540);
            this.Name = "LicenseAgreementDialog";
            this.Padding = new System.Windows.Forms.Padding(3);
            this.ShowFooter = true;
            this.ShowHeader = true;
            this.ShowIcon = false;
            this.ShowInTaskbar = true;
            this.Controls.SetChildIndex(this.CaptionControl, 0);
            this.Controls.SetChildIndex(this.BodyControl, 0);
            this.BodyControl.ResumeLayout(false);
            this.BodyControl.PerformLayout();
            this.RadioPanel.ResumeLayout(false);
            this.RadioPanel.PerformLayout();
            this.ResumeLayout(false);

        }
    }
}
