//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2022. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

namespace System.Windows.Forms
{
    public class CMYK
    {
        protected double C;
        protected double M;
        protected double Y;
        protected double K;

        public double Cyan
        {
            get { return C; }
            set
            {
                C = value;
                C = C > 1 ? 1 : C < 0 ? 0 : C;
            }
        }

        public double Magenta
        {
            get { return M; }
            set
            {
                M = value;
                M = M > 1 ? 1 : M < 0 ? 0 : M;
            }
        }

        public double Yellow
        {
            get { return Y; }
            set
            {
                Y = value;
                Y = Y > 1 ? 1 : Y < 0 ? 0 : Y;
            }
        }

        public double Key
        {
            get { return K; }
            set
            {
                K = value;
                K = K > 1 ? 1 : K < 0 ? 0 : K;
            }
        }
    }
}
