//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2022. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

using System.ComponentModel;
using System.Drawing;
using System.Resources;

namespace System.Windows.Forms
{
    [ToolboxItem(false)]
    public partial class ApplicationAboutEdit : UserControl
    {
        private PanelEdit panelLogo;
        private ImageEdit imageLogo;
        private PanelEdit panelProduct;
        private LabelEdit labelProduct;
        private LabelEdit labelCopyright;
        private TabEdit tabProduct;
        private GridViewEdit listProduct;
        private ButtonEdit buttonTermsOfUse;
        private GridViewEdit listDataProviders;

        public ApplicationAboutEdit()
        {
            InitializeComponent();

            panelLogo.BorderStyle = Border3DSide.All;
            panelLogo.BackgroundImage = ImagesCustom.Background;
            panelLogo.BackgroundImageLayout = ImageLayout.Tile;

            imageLogo.AutoSize = true;
            imageLogo.BackColor = Color.Transparent;
            imageLogo.Image = ImagesCustom.Banner;

            buttonTermsOfUse.Click += OnTermsOfUseLinkClicked;

            tabProduct.ShowHeader = true;
            TabEditPage productPage = tabProduct.AddPage(listProduct = new GridViewEdit());
            TabEditPage providersPage = tabProduct.AddPage(listDataProviders = new GridViewEdit());

            listProduct.Parent.Padding = new Padding(3, 0, 3, 3);
            listDataProviders.Parent.Padding = new Padding(3, 0, 3, 3);

            Localization.Register(this, e => OnProductsViewColumnLayout());
            Localization.Register(this, e => OnDataProvidersColumnLayout());
            Localization.Register(buttonTermsOfUse, e => buttonTermsOfUse.Text = e("TermsOfUse"));
            Localization.Register(labelCopyright, e => labelCopyright.Text = e("LegalCopyright"));
            Localization.Register(labelProduct, e => labelProduct.Text = string.Concat(ApplicationEnvironment.ProductName, " - ", e(ApplicationEnvironment.ProductLicense), " - ", ApplicationEnvironment.ProductVersion));
            Localization.Register(productPage, e => productPage.Text = e("InstalledModules"));
            Localization.Register(providersPage, e => providersPage.Text = e("InstalledDataProviders"));

            listProduct.View.ColumnLayout += OnProductsViewColumnLayout;
            listDataProviders.View.ColumnLayout += OnDataProvidersColumnLayout;
        }

        public virtual void SetDataSource(IPropertyGetter value)
        {
            listProduct.DataSource = value["Products"];
            listDataProviders.DataSource = value["DataProviders"];
        }

        protected void OnProductsViewColumnLayout()
        {
            if (listProduct.Columns.Contains("Enabled"))
            {
                listProduct.Columns["Enabled"].MinWidth = 48;
            }

            if (listProduct.Columns.Contains("DisplayName"))
            {
                listProduct.Columns["DisplayName"].MinWidth = 200;
            }

            if (listProduct.Columns.Contains("Author"))
            {
                listProduct.Columns["Author"].MinWidth = 120;
            }

            if (listProduct.Columns.Contains("Version"))
            {
                listProduct.Columns["Version"].MinWidth = 70;
                listProduct.Columns["Version"].TextAlign = ContentAlignment.MiddleRight;
            }

            listProduct.Redraw();
        }

        protected void OnDataProvidersColumnLayout()
        {
            if (listDataProviders.Columns.Contains("Enabled"))
            {
                listDataProviders.Columns["Enabled"].MinWidth = 48;
            }

            if (listDataProviders.Columns.Contains("DisplayName"))
            {
                listDataProviders.Columns["DisplayName"].MinWidth = 200;
            }

            if (listDataProviders.Columns.Contains("Author"))
            {
                listDataProviders.Columns["Author"].MinWidth = 120;
            }

            if (listDataProviders.Columns.Contains("Version"))
            {
                listDataProviders.Columns["Version"].MinWidth = 70;
                listDataProviders.Columns["Version"].TextAlign = ContentAlignment.MiddleRight;
            }

            listDataProviders.Redraw();
        }

        protected void OnTermsOfUseLinkClicked(object sender, EventArgs e)
        {
            if (LicenseAgreementDialog.IsAccepted(FindForm()))
            {
                return;
            }

            ApplicationEnvironment.Kill();
        }

        private void InitializeComponent()
        {
            this.tabProduct = new System.Windows.Forms.TabEdit();
            this.panelProduct = new System.Windows.Forms.PanelEdit();
            this.labelProduct = new System.Windows.Forms.LabelEdit();
            this.labelCopyright = new System.Windows.Forms.LabelEdit();
            this.panelLogo = new System.Windows.Forms.PanelEdit();
            this.buttonTermsOfUse = new System.Windows.Forms.ButtonEdit();
            this.imageLogo = new System.Windows.Forms.ImageEdit();
            this.panelProduct.SuspendLayout();
            this.panelLogo.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.imageLogo)).BeginInit();
            this.SuspendLayout();
            // 
            // tabProduct
            // 
            this.tabProduct.BackColor = System.Drawing.Color.Transparent;
            this.tabProduct.ColumnCount = 1;
            this.tabProduct.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tabProduct.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tabProduct.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tabProduct.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabProduct.Location = new System.Drawing.Point(6, 119);
            this.tabProduct.Margin = new System.Windows.Forms.Padding(0);
            this.tabProduct.Name = "tabProduct";
            this.tabProduct.Padding = new System.Windows.Forms.Padding(3, 0, 3, 3);
            this.tabProduct.RowCount = 2;
            this.tabProduct.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 0F));
            this.tabProduct.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tabProduct.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 0F));
            this.tabProduct.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tabProduct.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 0F));
            this.tabProduct.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tabProduct.Size = new System.Drawing.Size(467, 143);
            this.tabProduct.TabIndex = 8;
            // 
            // panelProduct
            // 
            this.panelProduct.Controls.Add(this.labelProduct);
            this.panelProduct.Controls.Add(this.labelCopyright);
            this.panelProduct.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelProduct.Location = new System.Drawing.Point(6, 66);
            this.panelProduct.Name = "panelProduct";
            this.panelProduct.Size = new System.Drawing.Size(467, 53);
            this.panelProduct.TabIndex = 7;
            // 
            // labelProduct
            // 
            this.labelProduct.Location = new System.Drawing.Point(10, 6);
            this.labelProduct.Name = "labelProduct";
            this.labelProduct.Padding = new System.Windows.Forms.Padding(3);
            this.labelProduct.Size = new System.Drawing.Size(54, 17);
            this.labelProduct.TabIndex = 7;
            this.labelProduct.TabStop = false;
            this.labelProduct.Text = "Product";
            this.labelProduct.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // labelCopyright
            // 
            this.labelCopyright.Location = new System.Drawing.Point(10, 29);
            this.labelCopyright.Name = "labelCopyright";
            this.labelCopyright.Padding = new System.Windows.Forms.Padding(3);
            this.labelCopyright.Size = new System.Drawing.Size(64, 17);
            this.labelCopyright.TabIndex = 8;
            this.labelCopyright.TabStop = false;
            this.labelCopyright.Text = "Copyright";
            this.labelCopyright.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // panelLogo
            // 
            this.panelLogo.Controls.Add(this.buttonTermsOfUse);
            this.panelLogo.Controls.Add(this.imageLogo);
            this.panelLogo.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelLogo.Location = new System.Drawing.Point(6, 6);
            this.panelLogo.Name = "panelLogo";
            this.panelLogo.Padding = new System.Windows.Forms.Padding(10);
            this.panelLogo.Size = new System.Drawing.Size(467, 60);
            this.panelLogo.TabIndex = 1;
            // 
            // buttonTermsOfUse
            // 
            this.buttonTermsOfUse.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonTermsOfUse.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(243)))), ((int)(((byte)(243)))));
            this.buttonTermsOfUse.Cursor = System.Windows.Forms.Cursors.Default;
            this.buttonTermsOfUse.FlatAppearance.BorderSize = 0;
            this.buttonTermsOfUse.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttonTermsOfUse.Location = new System.Drawing.Point(329, 31);
            this.buttonTermsOfUse.Name = "buttonTermsOfUse";
            this.buttonTermsOfUse.Size = new System.Drawing.Size(129, 23);
            this.buttonTermsOfUse.TabIndex = 10;
            this.buttonTermsOfUse.Text = "Terms Of Use";
            this.buttonTermsOfUse.Title = "";
            this.buttonTermsOfUse.UseVisualStyleBackColor = false;
            // 
            // imageLogo
            // 
            this.imageLogo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.imageLogo.Location = new System.Drawing.Point(10, 10);
            this.imageLogo.Name = "imageLogo";
            this.imageLogo.Size = new System.Drawing.Size(447, 40);
            this.imageLogo.TabIndex = 1;
            this.imageLogo.TabStop = false;
            // 
            // ApplicationAboutEdit
            // 
            this.Controls.Add(this.tabProduct);
            this.Controls.Add(this.panelProduct);
            this.Controls.Add(this.panelLogo);
            this.Name = "ApplicationAboutEdit";
            this.Padding = new System.Windows.Forms.Padding(6);
            this.Size = new System.Drawing.Size(479, 268);
            this.panelProduct.ResumeLayout(false);
            this.panelProduct.PerformLayout();
            this.panelLogo.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.imageLogo)).EndInit();
            this.ResumeLayout(false);

        }
    }
}
