//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2022. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

using System.Drawing;
using System.Resources;
using System.Windows.Forms;
using System.Workspace;

namespace System.Windows.Modules.Data
{
    internal class KmlFileHandler : ApplicationDataFile
    {
        static KmlFileHandler()
        {
            ControlType = ApplicationEnvironment.GetType("System.Data.Kml.KmlMapLayerControl, System.Data.Kml");
        }

        public KmlFileHandler()
        {
            Extensions.Add("KML");
            Extensions.Add("KMZ");
        }

        protected readonly static Type ControlType;

        public override bool Available
        {
            get { return base.Available && ControlType.HasValue(); }
        }

        public override string Name
        {
            get { return "KML"; }
        }

        public override bool AllowSelectLayers
        {
            get { return true; }
        }

        public override MapWorkspace CreateWorkspace()
        {
            return new KmlWorkspace();
        }

        public override Image GetIcon(string extension, int maxWidth)
        {
            return Images048.Kml.ReSize(maxWidth);
        }

        protected override void OnBeginRead(ApplicationFileEventArgs e)
        {
            var control = Activator.CreateInstance(ControlType) as MapLayerControl;

            control.ExecuteCommand("Hide Location");
            control.ExecuteCommand(Constants.Data.DataSource, e.FileName);

            using (var dialog = new ApplicationForm { FormBorderStyle = FormBorderStyle.FixedDialog })
            {
                dialog.ShowFooter = true;
                dialog.Size = new Size(600, 460);
                dialog.Body.Controls.Add(control);

                if (dialog.ShowDialog(e.Project.Application.Form) == DialogResult.OK)
                {
                    control.CreateLayers(e.Project.Workspace);
                }
                else
                {
                    e.Cancel = true;
                }
            }
        }

        protected override void OnRead(ApplicationFileEventArgs e)
        {
        }
    }
}
