//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2022. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

using System.ComponentModel;
using System.Drawing;
using System.Resources;

namespace System.Windows.Forms
{
    partial class ListViewEdit
    {
        public class CheckBoxColumn : Column
        {
            public CheckBoxColumn()
                : base(SizeType.Absolute, 19)
            {
                AllowResize = false;
                Dock = DockStyle.None;
                Anchor = AnchorStyles.None;
            }

            public override bool AllowSort
            {
                get { return false; }
                set { }
            }

            public override bool CanFilter
            {
                get { return false; }
            }

            public override bool AllowFilter
            {
                get { return false; }
                set { }
            }

            public bool Checked
            {
                get
                {
                    if (Owner.HasValue())
                    {
                        return Owner.View.Rows.IsChecked();
                    }

                    return false;
                }
                set
                {
                    if (Owner.HasValue())
                    {
                        Owner.View.Rows.SetChecked(value);
                        Owner.View.Invalidate(false);
                        Invalidate(false);
                    }
                }
            }

            [Browsable(false)]
            [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
            public override Image Image
            {
                get { return Checked ? Images016.Checked : Images016.Unchecked; }
                set { }
            }

            protected override void OnClick(EventArgs e)
            {
                Checked = !Checked;
            }
        }
    }
}