//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2022. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

using System.Drawing;

namespace System.Windows.Forms.Ribbon
{
    public class RibbonPage : TabEditPage
    {
        internal RibbonPage(string name)
            : base(name)
        {
            Name = name;
            MinimumSize = new Size(100, 100);

            Controls.Add(Content = new TablePanelEdit
            {
                Name = name,
                RowCount = 3,
                Dock = DockStyle.Top
            });

            Groups = new RibbonPageGroupCollection(this);

            Content.AddColumn(SizeType.Percent, 100);

            Localization.Register(this, e => Text = e(Name));
        }

        protected internal TablePanelEdit Content;

        public RibbonControl Ribbon
        {
            get { return Parent as RibbonControl; }
        }

        public override bool CanActive
        {
            get { return Ribbon.TabPages.IndexOf(this) > 0; }
        }

        public RibbonPageGroupCollection Groups
        {
            get;
            protected set;
        }

        public RibbonPageGroup this[string name]
        {
            get { return Groups[name]; }
        }

        protected override void OnPaint(PaintEventArgs e)
        {
            Ribbon.OnPaintPage(this, e);
            base.OnPaint(e);
        }
    }
}
